<a href="https://colab.research.google.com/github/Huyvubk/Python-programing/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# câu 1 : import module numpy và in ra version 

import numpy as np
import numpy
print (numpy.version.version)


1.19.5


In [ ]:
# câu 2 : Tạo mảng 1 chiều từ 0 đến 9

import numpy as np
data = np.arange(0,10)
print(data)
print(data.shape)
print(type(data.dtype))

[0 1 2 3 4 5 6 7 8 9]
(10,)
<class 'numpy.dtype'>


In [ ]:
# câu 3: Tạo một mảng boolean 3x3 với tất cả giá trị là True

import numpy as np

# Cách 1 :
arr1 = np.array([(True,True,True), (True,True,True),(True,True,True)], dtype = bool)
print(arr1)

# Cách 2 : 
arr2 = np.full((3,3),True,dtype=bool)
print(arr2)

# Cách 3:
arr3=np.ones((3, 3), dtype=bool)
print(arr3)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# câu 4 : Lấy những phần tử mà thoả mãn một điều kiện cho trước của mảng một chiều

import numpy as np

# tạo mảng một chiều từ 0 đến 9
arr = np.arange(10)
arr_chan = []
arr_le = []
print(arr)
# Tìm phần tử có giá rị lẻ 
for x in arr:
  if x % 2 == 0:
        arr_chan.append(x)
  else:
        arr_le.append(x)
print(arr_chan)
print(arr_le)
# Tìm phần tử có giá rị lẻ 
arr1 =arr[arr%2] == 1
print(arr1)


[0 1 2 3 4 5 6 7 8 9]
[0, 2, 4, 6, 8]
[1, 3, 5, 7, 9]
[False  True False  True False  True False  True False  True]


In [ ]:
# câu 5 : Thay thế phần tử thoả mãn điều kiện cho trước bằng 1 một giá khác

import numpy as np

# tạo mảng một chiều từ 0 đến 9
arr = np.arange(10)
print(arr)
# cách 1
# Thay thế phần tử có giá trị lẻ bằng -1
arr[arr%2==1] = -1
arr


[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
# câu 6 : Thay thế phần tử thoả mãn điều kiện cho trước bằng 1 một giá khác 
# nhưng không thay đổi mảng ban đầu

# Thay thế tất cả số lẻ bằng giá trị -1 nhưng mảng ban đầu không thay đổi

import numpy as np

# tạo mảng một chiều từ 0 đến 9
arr = np.arange(10)
arr_coppy=arr.copy()
print(arr)
print(arr_coppy)
arr[arr%2==1] = -1
arr
# # Cách 2 :
arr_out = np.where(arr%2==1,-1,arr)
print(arr_out)



[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
# câu 7 : Định dạng/chuyển mảng

# Chuyển mảng 1 chiều thành mảng 2 chiều có 2 hàng ( dòng )

import numpy as np

# tạo mảng 1d gồm 10 phần tử
a =np.arange(9)
# mảng 2 chiều có 2 hàng
b=np.resize(a, 10).reshape(2,5)
print(b)

In [ ]:
# câu 8:  xếp chồng 2 mảng theo chiều dọc

import numpy as np

# tạo data
a = np.array(([0, 1, 2, 3, 4],[5, 6, 7, 8, 9]))
print("a:",a)
b = np.array(([1, 1, 1, 1, 1],[1, 1, 1, 1, 1]))
print("b:",b)
# Cách 1 : 
result1 = np.concatenate((a,b), axis =0)
print("result1:\n", result1)
# Cách 2 : 
result2  = np.vstack([a,b])
print("result2:\n", result2)
# Cách 3 : 
result3 = np.r_[a,b]
print("result3:\n", result3)

a: [[0 1 2 3 4]
 [5 6 7 8 9]]
b: [[1 1 1 1 1]
 [1 1 1 1 1]]
result1:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
result2:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
result3:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
# câu 9 : xếp chồng 2 mảng theo chiều ngang

import numpy as np

# tạo data
a = np.array(([0, 1, 2, 3, 4],[5, 6, 7, 8, 9]))
print("a:",a)
b = np.array(([1, 1, 1, 1, 1],[1, 1, 1, 1, 1]))
print("b:",b)
# Cách 1 : 
result1 = np.concatenate((a,b), axis =1)
print("result1:\n", result1)
# Cách 2 : 
result2  = np.hstack([a,b])
print("result2:\n", result2)
# Cách 3 : 
result3 = np.c_[a,b]
print("result3:\n", result3)

In [ ]:
# câu 10

import numpy as np

# chỉ dùng hàm numpy có sẵn với mảng a như bên dưới
a = np.array([1,2,3])
print(a)

# tạo mảng mới lặp lại mỗi phần tử lên 3 lần
a1 = np.repeat(a,3)
print(a1)
# tạo mảng mới lặp lại mảng tất cả phần tử lên 3 lần
a2 = np.tile(a,3)
print(a2)

In [ ]:
# câu 11: Lấy phần tử chung của 2 mảng a và b 

import numpy as np

a = np.array([1,2,3,2,3,4,3,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Lấy phần tử chung của 2 mảng a và b 
c = np.intersect1d(a,b)
c

array([2, 4])

In [ ]:
# câu 12 : Xoá phần tử từ 1 mảng mà tồn tại trong 1 mảng khác

import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# Từ mảng a xoá tất cả các phần tử mà đã có trong mảng b
c = np.setdiff1d(a,b)
c

array([1, 2, 3, 4])

In [ ]:
# câu 13: 

import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Lấy tất cả vị trí nơi giá trị các phần tử của 2 mảng a,b giống nhau
c = np.where(a==b)
c


(array([1, 3, 5, 7]),)

In [ ]:
# câu 14 : Lấy tất cả các giá trị trong 1 phạm vi cho trước từ 1 mảng

import numpy as np

a = np.array([2,6,1,9,10,3,27])

# tìm tất cả vị trí của các phần tử có giá trị trong phạm vi [5,10]
#cach 1:
index1 = np.where((a>=5)&(a<=10))
print(a[index1])
# # cach 2:
# index = np.where(np.logical_and(a>=5,a<=10))
# print(a[index])
# # cach 3:
# a[(a>=5)&(a<=10)]
# print(a[index])

[ 6  9 10]
[ 6  9 10]


In [ ]:
# câu 15 : Tạo hàm xử lý trên mảng numpy

import numpy as np

def maxx(x,y):
    # Lấy số lớn nhất nhất trong 2 số
    if x >= y :
        return x
    else:
        return y

a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

# numpy.vectorize lấy hàm maxx: x,y và biến nó thành maxx: a[] -> b[].
# cach 1 :
# max = np.vectorize(maxx)
# max(a,b)
#cach 2 :
# print(np.maximum(a,b))
# cach 3 :
print(np.where(a<b,b,a))

[6 7 9 8 9 7 5]


In [ ]:
import numpy as np

# lấy giá trị lớn hơn giữa a và b
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])


# dùng hàm maximum để
# print(np.maximum(a,b))

# dùng hàm where 
print(np.where(a<b,b,a))

array([6, 7, 9, 8, 9, 7, 5])

In [ ]:
# câu 16 : Hoán các cột trong mảng 2 chiều 

import numpy as np

# cho mảng arr có shape 3x3
arr = np.arange(9).reshape(3,3)
print(arr)
# Hoán cột có index 0 và index 1 trong mảng arr
print(arr[:,[1,0,2]])

In [ ]:
# câu 17 :  Hoán 2 hàng trong mảng 2 chiều 

import numpy as np

# cho mảng arr có shape 3x3
arr = np.arange(9).reshape(3,3)
print(arr)

# Hoán dòng có index 0 và index 1 trong mảng arr
print(arr[[1,0,2],:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [ ]:
# câu 18 : 

import numpy as np

# cho mảng arr có shape 3x3
arr = np.arange(9).reshape(3,3)
print(arr)
# Đoản ngược hàng (dòng) trong mảng 2 chiều
print(arr[::-1,:])


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [ ]:
# câu 19 

import numpy as np

# cho mảng arr có shape 3x3
arr = np.arange(9).reshape(3,3)
print(arr)
# Đoản ngược cột trong mảng 2 chiều
print(arr[:,::-1])


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [ ]:
# Câu 20 :  Tạo mảng 2 chiều chứa số random kiểu float từ 5 đến 10

import numpy as np


# Tạo mảng 2 chiều 5x3 từ 5 đến 10
arr =   np.random.uniform(5,10,size=(5,3))
arr
# Cách Dùng hàm random.uniform 



array([[8.41823442, 5.65479953, 5.65891761],
       [5.98194824, 6.22946116, 8.26254591],
       [7.54845492, 8.64016225, 7.97005181],
       [7.79981466, 9.02576892, 5.49124682],
       [6.96202432, 6.03513194, 7.55749151]])

In [ ]:
# câu 21 

import numpy as np

# cho mảng a chứa các số ngẫu nhiên từ [1, 50)
a = np.random.uniform(1,50,20)
print(a)

# Thay thế tất cả các giá trị lớn hơn một giá trị cho trước thành một phạm vi [10,30]
# Thay thế tất cả các giá trị lớn hơn 30 thành 30 và dưới 10 thành 10
# Cách 1 : dùng hàm np.clip  
result1 = np.clip(a,10,30)
print(result1)

# Cách 2 : dùng hàm np.where
result2 = np.where(a<10,10,np.where(a>30,30,a))
print(result2)


In [ ]:
# câu 22: Lấy vị trí của n giá trị đứng đầu từ một mảng numpy

import numpy as np

# cho mảng a chứa các số ngẫu nhiên từ [1, 50)
a = np.random.uniform(1,50, 20)
print(a)

# Lấy vị trí của 5 giá trị lớn nhấttrong một mảng a

# Cách 1 : dùng hàm np.argsort() 
print('vị trí:',np.argsort(a)[-5:])
print('giá trị:',a[np.argsort(a)[-5:]])

# Cách 2 : dùng hàm sort() 
print('vị trí:',np.argpartition(a,-5)[-5:])
print('giá trị:',a[np.argpartition(a,-5)[-5:]])


[ 4.53974581 27.12186135 33.96868037 26.91208459 31.99186439 48.03069164
 47.17714253 36.91467116  1.91501098 22.80288204 17.54257486 11.6762493
 23.83445951 23.12252517 16.10140513 18.48834104  2.40421636 12.04300776
 20.05569409 43.39239807]
vị trí: [ 2  7 19  6  5]
giá trị: [33.96868037 36.91467116 43.39239807 47.17714253 48.03069164]
vị trí: [ 2  7 19  5  6]
giá trị: [33.96868037 36.91467116 43.39239807 48.03069164 47.17714253]


In [ ]:
# câu 23: Chuyển đổi một mảng chứa nhiều mảng thành một mảng 1d phẳng

import numpy as np


# cho array_of_arrays như sau
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
print('array_of_arrays: ', array_of_arrays)

# Chuyển đổi array_of_arrays thành mảng 1d tuyến tính phẳng 
# cách 1 :
arr_2d = np.array([a for arr in array_of_arrays for a in arr])
print("arr moi :",arr_2d)
# cách 2 :
arr_2d = np.concatenate(array_of_arrays)
print("arr moi :",arr_2d)
# cách 3 :
arr_2d = np.hstack(array_of_arrays)
print("arr moi :",arr_2d)

array_of_arrays:  [array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
arr moi : [0 1 2 3 4 5 6 7 8 9]
arr moi : [0 1 2 3 4 5 6 7 8 9]
arr moi : [0 1 2 3 4 5 6 7 8 9]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  # This is added back by InteractiveShellApp.init_path()


In [ ]:
# câu 24: Tìm giá trị lớn nhất trong mỗi hàng của mảng 2d 

import numpy as np

# cho mảng a
a = np.random.randint(1, 10, [5,3])
print(a)


# Cách 1 : dùng np.amax
result = np.amax(a, axis=1)
print(result)

#Cách 2 : dung np.apply_along_axis và np.max
result = np.apply_along_axis(np.max,axis=1,arr=a)
print(result)

In [ ]:
# câu 25

import numpy as np

# cho mảng a
a = np.random.randint(1, 10, [5,3])
print(a)
result1 = np.apply_along_axis(np.max,axis=1,arr=a)
print(result1)
result2 = np.apply_along_axis(np.min,axis=1,arr=a)
print(result2)
# tính tỉ số min/max cho mỗi hàng trong mảng a
c = result2/result1
print(c)


[[8 3 3]
 [7 3 1]
 [4 8 7]
 [6 7 6]
 [7 6 7]]
[8 7 8 7 7]
[3 1 4 6 6]
[0.375      0.14285714 0.5        0.85714286 0.85714286]


In [ ]:
# câu 26: Tìm các vị trí có giá trị trùng lặp trong một mảng numpy

import numpy as np

# cho mảng a
a = np.random.randint(0, 5, 10)
print(a)

# Tìm các phần tử trùng lặp (lần xuất hiện thứ 2 trở đi) trong mảng đã cho
# và đánh dấu chúng là True. Lần đầu tiên xuất hiện là False.

# hint: dùng np.full và np.unique



[3 4 2 1 0 2 2 4 2 0]


In [ ]:
# câu 27: loại bỏ tất cả các giá trị còn thiếu (np.nan) trong một mảng

import numpy as np

# cho mảng a
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
print(a)

# bỏ tất cả các giá trị nan từ một mảng numpy 1D
# cách 1 :
# print(a[np.logical_not(np.isnan(a))])
# cách 2 :
print(a[~np.isnan(a)])

[ 1.  2.  3. nan  5.  6.  7. nan]
[1. 2. 3. 5. 6. 7.]


In [ ]:
# câu 28: 

import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

# tính khoảng cách giữa hai mảng a và b, dùng np.linalg.norm
dist = np.linalg.norm(a-b)
dist

6.708203932499369

In [ ]:
# câu 29: Tìm tất cả các cực đại cục bộ (hay còn gọi các đỉnh) trong một mảng 1d

import numpy as np



# cho mảng a như sau
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

# Tìm tất cả các đỉnh trong một mảng numpy 1D. 
# Đỉnh là các điểm được bao quanh bởi các giá trị nhỏ hơn ở cả hai phía.

# hint: dùng np.diff và np.sign
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations


array([2, 5])